name: Android Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # Use Gradle 7.5.1 instead of Gradle 8.x
      - name: Force Gradle 7.5.1 Wrapper
        run: |
          ./gradlew wrapper --gradle-version 7.5.1
          chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Remove problematic Play Publisher plugin if present
      - name: Disable Play Publisher plugin
        run: |
          sed -i '/play-publisher/d' build.gradle || true
          sed -i '/com.github.triplet.play/d' build.gradle || true
          sed -i '/play-publisher/d' app/build.gradle || true
          sed -i '/com.github.triplet.play/d' app/build.gradle || true

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-launcher-assistant-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
